spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: fox
    password: foxpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 可选：保证每次连接协商后字符集一致
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
  security:
    jwt:
      issuer: "foxblog"
      access-token-seconds: 7200
      clock-skew-seconds: 30
      active-key:
        id: "k1"
        private-pem-location: "classpath:jwt/active-private.pem"
        public-pem-location: "classpath:jwt/active-public.pem"
        algorithm: "RS256"
      passive-keys:
        - id: "k0"
          public-pem-location: "classpath:jwt/passive-k0-public.pem"
          algorithm: "RS256"
      log-keys-at-startup: true