spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4
    username: fox
    password: foxpassword
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
        ddl-auto: validate     # 生产推荐 validate，不要 create-drop
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    jwt:
      issuer: "foxblog"
      # access token 有效期（秒）
      access-token-seconds: 7200
      # 允许的最大时钟偏差（秒）
      clock-skew-seconds: 30
      # 主签名私钥 PEM 路径（可使用 file: / classpath: 前缀）
      active-key:
        id: "k1"                       # kid
        private-pem-location: "classpath:jwt/active-private.pem"
        public-pem-location: "classpath:jwt/active-public.pem"
        algorithm: "RS256"              # 支持 RS256 / ES256 / ES384 / ES512
      # 历史密钥（只做验证，不再签发）
      passive-keys:
        - id: "k0"
          public-pem-location: "classpath:jwt/passive-k0-public.pem"
          algorithm: "RS256"
      # 是否在启动时打印 key 列表（生产建议 false）
      log-keys-at-startup: true
