spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4
    username: fox
    password: foxpassword
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings: false
      ddl-auto: create-drop  # 测试推荐 validate，不要 validate
      #ddl-auto: validate     # 生产推荐 validate，不要 create-drop
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
